/**
 * Represents the complete data model for a processed resume.
 * This is the primary object stored in the database/KV.
 */
interface Resume {
    id: string;
    companyName?: string;
    jobTitle?: string;
    imagePath: string; // Path to the generated visual preview in Puter FS
    resumePath: string; // Path to the original PDF file in Puter FS
    feedback: Feedback;
}

/**
 * A comprehensive evaluation report generated by the AI synthesis engine.
 */
interface Feedback {
    overallScore: number; // Aggregate performance indicator (0-100)
    
    /** Applicant Tracking System (ATS) optimization results. */
    ATS: {
        score: number;
        tips: {
            type: "good" | "improve";
            tip: string;
        }[];
    };

    /** Analysis of the language, vocabulary, and professional persona. */
    toneAndStyle: {
        score: number;
        tips: {
            type: "good" | "improve";
            tip: string;
            explanation: string;
        }[];
    };

    /** Evaluation of the work experience and impact descriptions. */
    content: {
        score: number;
        tips: {
            type: "good" | "improve";
            tip: string;
            explanation: string;
        }[];
    };

    /** Assessment of document layout, readability, and hierarchy. */
    structure: {
        score: number;
        tips: {
            type: "good" | "improve";
            tip: string;
            explanation: string;
        }[];
    };

    /** Verification of technical/soft skills alignment with the job title. */
    skills: {
        score: number;
        tips: {
            type: "good" | "improve";
            tip: string;
            explanation: string;
        }[];
    };
}